name: lotterynumbergen
description: A flutter application to generate random lottery numbers

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^4.0.4
  shared_preferences: ^0.5.6+2
  flutter_icons: ^1.0.0+1
  day_night_switch: ^0.0.2+1
  flutter_form_builder: ^3.8.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - i18n/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
